/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */

import { Customer } from "./Customer";
import { CustomerFindManyArgs } from "./CustomerFindManyArgs"
import { CustomerFindUniqueArgs } from "./CustomerFindUniqueArgs";
import { CreateCustomerArgs } from "./CreateCustomerArgs";
import { UpdateCustomerArgs } from "./UpdateCustomerArgs";
import { DeleteCustomerArgs } from "./DeleteCustomerArgs";
import { OrderFindManyArgs } from "src/order/base/OrderFindManyArgs";
import { Order } from "src/order/base/Order";
import { Address } from "src/address/base/Address";
import { CustomerCreateInput } from "./CustomerCreateInput";
import { CustomerWhereUniqueInput } from "./CustomerWhereUniqueInput";
import { CustomerUpdateInput } from "./CustomerUpdateInput";

export class CustomerServiceBase {
  constructor() {}

  async count(args: CustomerFindManyArgs): Promise<number> {
    throw new Error('Not Implemented');
  }

  async findMany(
    args: CustomerFindManyArgs
  ): Promise<Customer[]> {
    throw new Error('Not Implemented');
  }

  async findOne(args: CustomerWhereUniqueInput | CustomerFindUniqueArgs): Promise<Customer | null> {
    throw new Error('Not Implemented');
  }

  async create(args: CustomerCreateInput | CreateCustomerArgs): Promise<Customer> {
    throw new Error('Not Implemented');
  }

  async update(args: CustomerUpdateInput | UpdateCustomerArgs): Promise<Customer | null> {
    throw new Error('Not Implemented');
  }

  async delete(args: CustomerWhereUniqueInput | DeleteCustomerArgs): Promise<Customer> {
    throw new Error('Not Implemented');
  }

  async findOrders(
    parentId: string,
    args: OrderFindManyArgs
  ): Promise<Order[]> {
    throw new Error('Not Implemented');
  }

  async getAddress(parentId: string): Promise<Address | null> {
    throw new Error('Not Implemented');
  }
}
