import { OrderUpdateInput } from './OrderUpdateInput';
import { OrderWhereUniqueInput } from './OrderWhereUniqueInput';
import { OrderCreateInput } from './OrderCreateInput';
import { UpdateOrderArgs } from './UpdateOrderArgs';
import { CreateOrderArgs } from './CreateOrderArgs';
/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */

import { Customer } from "src/customer/base/Customer";
import { Product } from "src/product/base/Product";
import { Order } from "./Order";
import { OrderFindManyArgs } from "./OrderFindManyArgs";
import { OrderFindUniqueArgs } from "./OrderFindUniqueArgs";
import { DeleteOrderArgs } from './DeleteOrderArgs';

export class OrderServiceBase {
  constructor() {}

  async count(args: OrderFindManyArgs): Promise<number> {
    throw new Error('Not Implemented');
  }

  async findMany(args: OrderFindManyArgs): Promise<Order[]> {
    throw new Error('Not Implemented');
  }

  async findOne(args: OrderWhereUniqueInput | OrderFindUniqueArgs): Promise<Order | null> {
    throw new Error('Not Implemented');
  }

  async create(args: OrderCreateInput | CreateOrderArgs): Promise<Order> {
    throw new Error('Not Implemented');
  }

  async update(args: OrderUpdateInput | UpdateOrderArgs): Promise<Order> {
    throw new Error('Not Implemented');
  }
  async delete(args: OrderWhereUniqueInput | DeleteOrderArgs): Promise<Order> {
    throw new Error('Not Implemented');
  }

  async getCustomer(parentId: string): Promise<Customer | null> {
    throw new Error('Not Implemented');
  }

  async getProduct(parentId: string): Promise<Product | null> {
    throw new Error('Not Implemented');
  }
}
